version: "3.9"
services:
    # app:
    # web:

    mysql:
        image: mysql:8.0.27
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            TZ: "Asia/Tokyo"
        volumes:
            - mysql:/var/lib/mysql

    phpmyadmin:

volumes:
    mysql:
